export const APP_ROUTE = {
    home: '/',
    catalog: '/catalog',
    product: '/product',
    exchange: '/exchange',
    auth: '/auth',
    brands: '/brands',
    about: '/about',
    contact: '/contact',
    visit: '/visit',
    order: '/order',
    vipService: '/vipservice',
    cart: '/cart',
    subscribe: '/subscribe',
    favorites: '/favorites',
    alionaDoletskaya: '/AlionaDoletskaya',
    concierge: {
        root: '/concierge',
        product: '/concierge/product',
    },
    help: {
        all: '/help/all',
        delivery: '/help-delivery',
        return: '/help-return',
        publicOffer: '/help/public-offer',
        userAgreement: '/help/user-agreement',
    },
    sell: {
        create: '/sell-create',
        info: '/sell',
        infoBrands: '/sell/brands',
    },
    cabinet: {
        history: '/cabinet/history',
        sells: '/cabinet/sells',
        favorites: '/cabinet/favorites',
        waiting: '/cabinet/waiting',
        setting: '/cabinet/setting',
    },
} as const;
